const existingGenres = ["Drama", "Romance", "Horror", "Action", "Adventure", "Science-Fiction","Crime","Thriller"]
const cities = [
    'Jerusalem',
    'Tel Aviv',
    'West Jerusalem',
    'Haifa',
    'Ashdod',
    'Rishon LeZiyyon',
    'Petah Tiqwa',
    'Beersheba',
    'Netanya',
    'Holon',
    'Bnei Brak',
    'Rehovot',
    'Bat Yam',
    'Ramat Gan',
    'Ashkelon',
    'Jaffa',
    "Modi'in Makkabbim Re'ut",
    'Herzliya',
    'Kfar Saba',
    "Ra'anana",
    'Hadera',
    'Bet Shemesh',
    'Lod',
    'Nazareth',
    'Modiin Ilit',
    'Ramla',
    'Nahariyya',
    'Qiryat Ata',
    'Givatayim',
    'Qiryat Gat',
    'Acre',
    'Eilat',
    'Afula',
    "Karmi'el",
    'Hod HaSharon',
    'Umm el Fahm',
    'Tiberias',
    'Qiryat Mozqin',
    'Qiryat Yam',
    "Rosh Ha'Ayin",
    'Ness Ziona',
    'Qiryat Bialik',
    'Ramat HaSharon',
    'Dimona',
    'Et Taiyiba',
    'Yavne',
    'Or Yehuda',
    'Yehud-Monosson',
    'Safed',
    'Gedera',
    'Tamra',
    'Yehud',
    'Daliyat al Karmel',
    'Migdal Ha`Emeq',
    'Sakhnin',
    'Netivot',
    'Mevasseret Ziyyon',
    'Ofaqim',
    'Arad',
    'Gan Yavne',
    'Qiryat Shemona',
    'Kefar Yona',
    'maalot Tarshiha',
    'Nesher',
    'Tirah',
    'Shoham',
    'Sederot',
    'Rahat',
    'Tirat Karmel',
    'Maghar',
    "Giv'at Shmuel",
    'Ariel',
    'Kafr Kanna',
    'Judeida Makr',
    'Kafr Qasim',
    'Qalansuwa',
    "Bet She'an",
    'Azor',
    'Ganei Tikva',
    'Er Reina',
    'Even Yehuda',
    'Kafr Manda',
    'Iksal',
    'Rekhasim',
    'Nahf',
    'Beit Jann',
    'Herzliya Pituah',
    'El Fureidis',
    'Kfar Yasif',
    'Kabul',
    'Tel Mond',
    'Yeroham',
    'Deir Hanna',
    'Dabburiya',
    'Mazkeret Batya',
    'Bnei Ayish',
    'Bu`eina',
    'Jaljulya',
    'Bir el Maksur',
    'Bet Dagan',
  ]
const textValidator = (value) => {
    return  /^[a-zA-Z0-9_ ]*$/.test(value) && value.trim() !== ''
}
const numberValidator = (value) => {
    return  /^(19|20)\d{2}$/.test(value)
}

const srcValidator = (value) => {
    return value.trim() !== ''
}

const emailValidator = (value) => {
    return /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(value)
}

export default {existingGenres, textValidator, numberValidator,srcValidator,cities,emailValidator}
// 